# Generated by Django 2.1.5 on 2019-02-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rumah_Sakit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokter',
            name='nomortelepon',
        ),
        migrations.RemoveField(
            model_name='pasien',
            name='nomortelepon',
        ),
        migrations.AddField(
            model_name='dokter',
            name='nomor_telepon',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasien',
            name='nomor_telepon',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pasien',
            name='alamat',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resep',
            name='total_harga',
            field=models.CharField(max_length=25),
        ),
    ]
